### ISSUE TITLE
Error: "Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded." on chrome browser

### ISSUE THREAD

**Issue by musaby** [eric-therond/simplesoccer#1]
Simplesoccer works on Firefox but I get the error in Chrome ( Mac OS X - Mojave * Chrome version:70.0.3538.102 )

> 
WebSocket connection to 'wss://localhost:9193/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
    at d.WebGLRenderer.updateTexture (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:186:1237)
    at d.WebGLSpriteBatch.renderBatch (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:186:17365)
    at d.WebGLSpriteBatch.flush (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:186:17194)
    at d.WebGLSpriteBatch.render (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:186:12379)
    at c.Sprite.d.Sprite._renderWebGL (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:185:6856)
    at c.World.d.DisplayObjectContainer._renderWebGL (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:185:3247)
    at c.Stage.d.DisplayObjectContainer._renderWebGL (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:185:3247)
    at d.WebGLRenderer.renderDisplayObject (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:185:31313)
    at d.WebGLRenderer.render (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:185:30913)
    at c.Game.updateRender (file:///Users/bilgisayarx/Desktop/simplesoccer-master/public/js/vendor.js:189:30424)

**Comment by eric-therond** [comment]
Hello
I have updated the readme, could you try this :
```bash
npm install -g brunch
brunch w --server
```
The application will be available at http://localhost:9192

Eric
